### ISSUE TITLE
Why do you not use something like Redsmin?

### ISSUE THREAD

**Issue by FGRibreau** [snip77/redis_admin#6]
Hello!

Just discovered your project and I wonder why you would not use a full GUI & monitoring tool like [Redsmin](https://www.redsmin.com) and build your own instead?

**Comment by omid-reza** [comment]
i want to create a nice view to manage redis ! with beatiful themes! i prefer to user this kind tools to manage tecs!

**Comment by FGRibreau** [comment]
Oh nice, could you give me some screenshots on how it renders?

**Comment by omid-reza** [comment]
Yes.let me take a screnshot in 12 hour.now i dont have access to my laptop.

**Comment by omid-reza** [comment]
You can see a few demo screen here [https://drive.google.com/drive/folders/1ekGgLQM4gvjeYDbsrxDQN2jTYRvTNaS4?usp=sharing](https://drive.google.com/drive/folders/1ekGgLQM4gvjeYDbsrxDQN2jTYRvTNaS4?usp=sharing)

**Comment by FGRibreau** [comment]
Hello !
The folder does not seem to be publicly accessible, I can’t open it :s

**Comment by omid-reza** [comment]
I have access (any one should access) with [https://drive.google.com/drive/folders/1ekGgLQM4gvjeYDbsrxDQN2jTYRvTNaS4?usp=sharing](https://drive.google.com/drive/folders/1ekGgLQM4gvjeYDbsrxDQN2jTYRvTNaS4?usp=sharing)

But if you cant access let me upload in github server and project folder in a few hour

**Comment by FGRibreau** [comment]
Got the access, thx :+1:
